"""empty message

Revision ID: 293c6eae1bb7
Revises: 196bcc3133cb
Create Date: 2015-11-30 14:21:23.981475

"""

# revision identifiers, used by Alembic.
revision = '293c6eae1bb7'
down_revision = '196bcc3133cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('superuser', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'superuser')
    ### end Alembic commands ###
