"""empty message

Revision ID: 59b1983baaa0
Revises: 44b4fd37b54e
Create Date: 2015-12-01 11:00:44.599240

"""

# revision identifiers, used by Alembic.
revision = '59b1983baaa0'
down_revision = '44b4fd37b54e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    ### end Alembic commands ###
